config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "pages#home"
   get "/about", to: "pages#about"
   resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
validates :title, presence: true, length: { minimum: 6, maximum: 100}
validates :description, presence: true, length: { minimum: 10 , maximum: 300}
validates :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
def show
    @article = Article.find(params[:id])
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def home
    # render html: "Hello World!"
    end
    def about
    end

end
                     

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/show.html.erb
<h1>Showing Article Details</h1>
<pre><strong>Title:   </strong><%=@article.title%></pre>
<pre><strong>Description:   </strong><%=@article.description%></pre>
<pre><strong>Author:  </strong><%=@article.author%></pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaAman</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is About</h1>
<%= link_to "Home", root_path%>

app/views/pages/home.html.erb
<h1>This is Home</h1>
<%= link_to "About", about_path%>
<%= link_to "Articles", articles_path%>